# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
  - main
pool:
  vmImage: "windows-latest"

stages:
  - stage: BuildStage
    displayName: Build Stage
    jobs:
    - job: BuildNuget
      displayName: Build Nuget packages
      variables:
        BuildConfiguration: release
      steps:
    
       - task: DotNetCoreCLI@2
         inputs:
           command: 'restore'
           projects: '**/*.csproj'
           restoreArguments: '--configuration $(BuildConfiguration)'
           feedsToUse: 'select'
        
       - task: DotNetCoreCLI@2
         inputs:
            command: 'build'
            projects: '**/*.csproj'
            arguments: '--configuration $(BuildConfiguration)'
      
       - task: DotNetCoreCLI@2
         inputs:
            command: 'pack'
            packagesToPack: '**/*.csproj'
            versioningScheme: 'off'

       - task: DotNetCoreCLI@2
         inputs:
            command: 'push'
            packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
            nuGetFeedType: 'internal'
            publishVstsFeed: 'b25685c0-52a1-428b-b5e3-36e4cf48810c/e91fbd15-3ba8-4c21-8905-834c86b86e33'